### ISSUE TITLE
请不要污染开源环境

### ISSUE THREAD

**Issue by primejava** [jinfagang/weibo_terminater#58]
请不要把标题党的作风带到开源社区来,你这样会污染这个环境.

Please don't bring the style of the title party to the open source community, you will pollute the environment.

**Comment by jinfagang** [comment]
Hi, I don't know what's your mean? I haven't make a penny money from community nor got any benefits from you, I just written some tools for anyone else could use it.
This project is not maintained any longer since last year but I believe most of codes can running on scrap data from weibo, if they broken, it's not mine fault just weibo upgraded their website. 
I have no passion or time to always maintain this but I'll do what I need to do to help others conveniently access data. Thanks.
